VAR_METRIC="tarantula"
java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain  -location /Users/marekmazur/astor/defects4j/math-95 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.distribution.FDistributionTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-95/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-95/ /Users/marekmazur/Desktop/Results/math-95/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}')  \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-85 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.distribution.NormalDistributionTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-85/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-85/ /Users/marekmazur/Desktop/Results/math-85/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-84 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.optimization.direct.MultiDirectionalTest:org.apache.commons.math.optimization.direct.MultiDirectionalTest: -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-84/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-84/ /Users/marekmazur/Desktop/Results/math-84/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-82 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.optimization.linear.SimplexSolverTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-82/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-82/ /Users/marekmazur/Desktop/Results/math-82/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-81 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.linear.EigenDecompositionImplTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-81/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-81/ /Users/marekmazur/Desktop/Results/math-81/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-80 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.linear.EigenDecompositionImplTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-80/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-80/ /Users/marekmazur/Desktop/Results/math-80/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-78 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.ode.events.EventStateTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-78/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-78/ /Users/marekmazur/Desktop/Results/math-78/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-74 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.ode.nonstiff.AdamsMoultonIntegratorTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-74/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-74/ /Users/marekmazur/Desktop/Results/math-74/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-73 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.analysis.solvers.BrentSolverTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-73/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-73/ /Users/marekmazur/Desktop/Results/math-73/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-71 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.ode.nonstiff.ClassicalRungeKuttaIntegratorTest:org.apache.commons.math.ode.nonstiff.DormandPrince853IntegratorTest: -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-71/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-71/ /Users/marekmazur/Desktop/Results/math-71/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-70 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.analysis.solvers.BisectionSolverTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-70/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-70/ /Users/marekmazur/Desktop/Results/math-70/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-64 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.optimization.general.MinpackTest:org.apache.commons.math.optimization.general.MinpackTest: -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-64/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-64/ /Users/marekmazur/Desktop/Results/math-64/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-44 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.ode.events.EventStateTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-44/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-44/ /Users/marekmazur/Desktop/Results/math-44/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-40 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-40/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-40/ /Users/marekmazur/Desktop/Results/math-40/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-39 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math.ode.nonstiff.DormandPrince853IntegratorTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-39/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-39/ /Users/marekmazur/Desktop/Results/math-39/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-32 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math3.geometry.euclidean.threed.PolyhedronsSetTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-32/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-32/ /Users/marekmazur/Desktop/Results/math-32/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-20 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math3.optimization.direct.CMAESOptimizerTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-20/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-20/ /Users/marekmazur/Desktop/Results/math-20/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-8 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math3.distribution.DiscreteRealDistributionTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-8/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-8/ /Users/marekmazur/Desktop/Results/math-8/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-7 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math3.ode.nonstiff.DormandPrince853IntegratorTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-7/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-7/ /Users/marekmazur/Desktop/Results/math-7/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-5 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math3.complex.ComplexTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-5/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-5/ /Users/marekmazur/Desktop/Results/math-5/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') \
; java -cp target/astor-*-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -location /Users/marekmazur/astor/defects4j/math-2 -mode jgenprog -package org.apache.commons -jvm4testexecution /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin -failing org.apache.commons.math3.distribution.HypergeometricDistributionTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes/ -bintestfolder /target/test-classes/ -stopfirst true -dependencies /Users/marekmazur/astor/examples/libs/junit-4.4.jar -maxgen 1000000 -seed 10 -maxtime 60 -scope local -stopfirst true -flthreshold 0 -population 1 -faultlocalization flacoco | tee /Users/marekmazur/Desktop/Results/math-2/$VAR_METRIC/log.txt \
; cp -R /Users/marekmazur/astor/output_astor/AstorMain-math-2/ /Users/marekmazur/Desktop/Results/math-2/$VAR_METRIC/ \
; kill -9 $(ps -ef | grep "java" | grep -v grep | awk '{print $2}') 


